name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-clj:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Java 11
        uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: "11"

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@13.6.0
        with:
          cli: latest

      - name: Run tests
        run: bin/test
